# Generated by Django 6.1.1 on 2026-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="diary_images/",
                verbose_name="Фотография",
            ),
        ),
    ]
