upstream web_app {
    server web:8000;
}

server {
    listen 80;
    server_name localhost;

    client_max_body_size 20M; # Ensures larger image uploads don't trigger 413 errors

    # Proxy normal view queries directly to Gunicorn
    location / {
        proxy_pass http://web_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Serve static assets compiled by collectstatic
    location /static/ {
        alias /app/staticfiles/;
    }

    # Serve user uploaded diary entry images
    location /media/ {
        alias /app/mediafiles/;
    }
}
